name: Push to Docker hub
run-name: "Push to docker hub: ${{ github.actor }} 🚀"

env:
  IMAGE_NAME: ${{inputs.IMAGE_NAME}}
  DOCKERFILE_LOCATION: ${{inputs.DOCKERFILE_LOCATION}}

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Build-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker image build -f $DOCKERFILE_LOCATION -t $IMAGE_NAME
      - name: Push Docker image
        run: |
          docker login -u ${{vars.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          docker image push $IMAGE_NAME
      - run: echo "🍏 This job's status is ${{ job.status }}."
