name: Push to Docker hub

on:
  workflow_call:
      inputs:
        dockerfile-location:
          required: true
          type: string
        image_name:
          required: true
          type: string
jobs:
  Build-Linux:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{inputs.image_name}}
      DOCKERFILE_LOCATION: ${{inputs.dockerfile-location}}
      DOCKER_USERNAME: ${{vars.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Validate Inputs
        run: |
          if [ -z "${{inputs.IMAGE_NAME}}" ]; then
            echo "IMAGE_NAME input is missing or empty."
            exit 1
          fi
          if [ -z "${{inputs.DOCKERFILE_LOCATION}}" ]; then
            echo "DOCKERFILE_LOCATION input is missing or empty."
            exit 1
          fi
      - name: Build Docker image
        run: docker image build -f $DOCKERFILE_LOCATION -t $IMAGE_NAME
      - name: Push Docker image
        run: |
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          docker image push $IMAGE_NAME
      - run: echo "🍏 This job's status is ${{ job.status }}."
