name: Push files to Amazon S3

on:
  workflow_call:
      inputs:
        bucket_region:
          required: true
          type: string
        folder_path: # Add this input
          required: true
          type: string
        bucket_name: # Add this input
          required: true
          type: string
jobs:
  Build-Linux:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.IAM_USER}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.IAM_SECRET}}
      AWS_REGION: ${{inputs.bucket_region}}
      FOLDER_PATH: /tmp/build/${{inputs.folder_path}}
      BUCKET_NAME: ${{inputs.bucket_name}}
    steps:
      - uses: actions/checkout@master
        with:
          repository: supergoongaming/sharedWorkflows
          ref: master
          path: src
      - name: Make Temporary folder
        run: mkdir -p /tmp/build
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: s3Artifact # Specify the name of the artifact
          path: /tmp/build
      - run: ls -lah src
      - run: ls -lah /tmp/build
      - name: Upload Files to S3
        run: go run main.go
        working-directory: src/s3Uploader
      - run: echo "🍏 This job's status is ${{ job.status }}."